game 'rdr3'
fx_version 'adamant'
rdr3_warning 'I acknowledge that this is a prerelease build of RedM, and I am aware my resources *will* become incompatible once RedM ships.'
lua54 'yes'
client_script 'client/main.lua'
server_script 'server/main.lua'
shared_script 'config.lua'
